/**
 * Mock CRM Data for Development
 * Remove this when backend is ready
 */

import type { Deal, Contact, Organization, Activity } from './crm-types'

// Mock Organizations
export const mockOrganizations: Organization[] = [
  {
    id: 'org-1',
    name: 'Deutscher Caritasverband e.V.',
    website: 'https://www.caritas.de',
    industry: 'Soziale Dienste',
    size: 'large',
    revenue: 5000000,
    email: 'info@caritas.de',
    phone: '+49 30 1234567',
    address: {
      street: 'Karlstraße 40',
      city: 'Freiburg',
      state: 'Baden-Württemberg',
      postalCode: '79104',
      country: 'Germany',
    },
    parentOrganizationId: null,
    contactCount: 5,
    dealCount: 3,
    tags: ['Social Services', 'Non-Profit'],
    customFields: {},
    ownerId: 'user-1',
    ownerName: 'Max Mustermann',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-11-01T14:30:00Z',
  },
  {
    id: 'org-2',
    name: 'NABU - Naturschutzbund Deutschland e.V.',
    website: 'https://www.nabu.de',
    industry: 'Umweltschutz',
    size: 'medium',
    revenue: 2500000,
    email: 'nabu@nabu.de',
    phone: '+49 30 9876543',
    address: {
      street: 'Charitéstraße 3',
      city: 'Berlin',
      state: 'Berlin',
      postalCode: '10117',
      country: 'Germany',
    },
    parentOrganizationId: null,
    contactCount: 3,
    dealCount: 2,
    tags: ['Environment', 'Conservation'],
    customFields: {},
    ownerId: 'user-1',
    createdAt: '2024-02-20T11:00:00Z',
    updatedAt: '2024-11-02T09:15:00Z',
  },
]

// Mock Contacts
export const mockContacts: Contact[] = [
  {
    id: 'contact-1',
    firstName: 'Anna',
    lastName: 'Schmidt',
    fullName: 'Anna Schmidt',
    email: 'anna.schmidt@caritas.de',
    phone: '+49 30 1234567',
    mobile: '+49 170 1234567',
    title: 'Geschäftsführerin',
    organizationId: 'org-1',
    organizationName: 'Deutscher Caritasverband e.V.',
    linkedinUrl: 'https://linkedin.com/in/anna-schmidt',
    twitterHandle: null,
    photoUrl: null,
    tags: ['Decision Maker', 'C-Level'],
    customFields: {},
    ownerId: 'user-1',
    ownerName: 'Max Mustermann',
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-11-01T14:30:00Z',
    lastContactedAt: '2024-10-28T16:00:00Z',
  },
  {
    id: 'contact-2',
    firstName: 'Thomas',
    lastName: 'Müller',
    fullName: 'Thomas Müller',
    email: 'thomas.mueller@nabu.de',
    phone: '+49 30 9876543',
    mobile: '+49 170 9876543',
    title: 'IT-Leiter',
    organizationId: 'org-2',
    organizationName: 'NABU - Naturschutzbund Deutschland e.V.',
    linkedinUrl: null,
    twitterHandle: '@tmueller',
    photoUrl: null,
    tags: ['Technical', 'IT'],
    customFields: {},
    ownerId: 'user-1',
    createdAt: '2024-02-20T11:30:00Z',
    updatedAt: '2024-11-02T09:15:00Z',
    lastContactedAt: '2024-10-30T10:00:00Z',
  },
]

// Mock Deals
export const mockDeals: Deal[] = [
  {
    id: 'deal-1',
    title: 'CRM Software Implementation',
    value: 45000,
    currency: 'EUR',
    stage: 'proposal',
    status: 'open',
    probability: 60,
    organizationId: 'org-1',
    organizationName: 'Deutscher Caritasverband e.V.',
    contactId: 'contact-1',
    contactName: 'Anna Schmidt',
    expectedCloseDate: '2024-12-15T00:00:00Z',
    actualCloseDate: null,
    createdAt: '2024-09-01T10:00:00Z',
    updatedAt: '2024-11-01T14:30:00Z',
    ownerId: 'user-1',
    ownerName: 'Max Mustermann',
    description: 'Full CRM implementation including data migration and training',
    source: 'Website',
    lostReason: null,
    tags: ['Software', 'Implementation'],
    customFields: {},
    activitiesCount: 8,
    emailsCount: 12,
    filesCount: 3,
    color: '#8B5CF6',
  },
  {
    id: 'deal-2',
    title: 'Annual License Renewal',
    value: 12000,
    currency: 'EUR',
    stage: 'negotiation',
    status: 'open',
    probability: 80,
    organizationId: 'org-2',
    organizationName: 'NABU - Naturschutzbund Deutschland e.V.',
    contactId: 'contact-2',
    contactName: 'Thomas Müller',
    expectedCloseDate: '2024-11-30T00:00:00Z',
    actualCloseDate: null,
    createdAt: '2024-10-01T09:00:00Z',
    updatedAt: '2024-11-02T09:15:00Z',
    ownerId: 'user-1',
    description: 'Annual software license renewal with support package',
    source: 'Existing Customer',
    lostReason: null,
    tags: ['Renewal', 'Recurring'],
    customFields: {},
    activitiesCount: 5,
    emailsCount: 8,
    filesCount: 1,
    color: '#3B82F6',
  },
  {
    id: 'deal-3',
    title: 'Training Workshop Package',
    value: 8500,
    currency: 'EUR',
    stage: 'qualified',
    status: 'open',
    probability: 40,
    organizationId: 'org-1',
    organizationName: 'Deutscher Caritasverband e.V.',
    contactId: 'contact-1',
    contactName: 'Anna Schmidt',
    expectedCloseDate: '2025-01-20T00:00:00Z',
    actualCloseDate: null,
    createdAt: '2024-10-15T14:00:00Z',
    updatedAt: '2024-10-28T16:00:00Z',
    ownerId: 'user-1',
    description: '3-day intensive training for 20 staff members',
    source: 'Referral',
    lostReason: null,
    tags: ['Training', 'Workshop'],
    customFields: {},
    activitiesCount: 3,
    emailsCount: 4,
    filesCount: 0,
    color: '#10B981',
  },
  {
    id: 'deal-4',
    title: 'Consulting Services',
    value: 25000,
    currency: 'EUR',
    stage: 'lead',
    status: 'open',
    probability: 20,
    organizationId: 'org-2',
    organizationName: 'NABU - Naturschutzbund Deutschland e.V.',
    contactId: 'contact-2',
    contactName: 'Thomas Müller',
    expectedCloseDate: '2025-02-28T00:00:00Z',
    actualCloseDate: null,
    createdAt: '2024-11-01T11:00:00Z',
    updatedAt: '2024-11-01T11:00:00Z',
    ownerId: 'user-1',
    description: 'Process optimization and digital transformation consulting',
    source: 'Cold Outreach',
    lostReason: null,
    tags: ['Consulting', 'Digital Transformation'],
    customFields: {},
    activitiesCount: 1,
    emailsCount: 2,
    filesCount: 0,
    color: '#F59E0B',
  },
]

// Mock Activities
export const mockActivities: Activity[] = [
  {
    id: 'activity-1',
    type: 'call',
    subject: 'Initial Discovery Call with Anna Schmidt',
    description: 'Discussed current CRM challenges and requirements',
    status: 'completed',
    priority: 'high',
    dueDate: '2024-10-28T00:00:00Z',
    dueTime: '14:00',
    completedAt: '2024-10-28T14:30:00Z',
    duration: 45,
    dealId: 'deal-1',
    dealTitle: 'CRM Software Implementation',
    contactId: 'contact-1',
    contactName: 'Anna Schmidt',
    organizationId: 'org-1',
    organizationName: 'Deutscher Caritasverband e.V.',
    ownerId: 'user-1',
    ownerName: 'Max Mustermann',
    assignedToId: 'user-1',
    assignedToName: 'Max Mustermann',
    location: 'Phone Call',
    attendees: [],
    outcome: 'Very positive - they need a solution within 2 months',
    createdAt: '2024-10-20T10:00:00Z',
    updatedAt: '2024-10-28T14:30:00Z',
  },
  {
    id: 'activity-2',
    type: 'meeting',
    subject: 'Product Demo - License Renewal',
    description: 'Show new features added in the latest version',
    status: 'pending',
    priority: 'medium',
    dueDate: '2024-11-10T00:00:00Z',
    dueTime: '10:00',
    completedAt: null,
    duration: 60,
    dealId: 'deal-2',
    dealTitle: 'Annual License Renewal',
    contactId: 'contact-2',
    contactName: 'Thomas Müller',
    organizationId: 'org-2',
    organizationName: 'NABU - Naturschutzbund Deutschland e.V.',
    ownerId: 'user-1',
    assignedToId: 'user-1',
    location: 'Online - Zoom',
    attendees: ['thomas.mueller@nabu.de'],
    outcome: null,
    createdAt: '2024-11-01T09:00:00Z',
    updatedAt: '2024-11-01T09:00:00Z',
  },
  {
    id: 'activity-3',
    type: 'task',
    subject: 'Send proposal document',
    description: 'Prepare and send detailed proposal including pricing',
    status: 'pending',
    priority: 'high',
    dueDate: '2024-11-05T00:00:00Z',
    dueTime: null,
    completedAt: null,
    duration: null,
    dealId: 'deal-1',
    dealTitle: 'CRM Software Implementation',
    contactId: 'contact-1',
    contactName: 'Anna Schmidt',
    organizationId: 'org-1',
    ownerId: 'user-1',
    assignedToId: 'user-1',
    location: null,
    attendees: [],
    outcome: null,
    createdAt: '2024-10-29T15:00:00Z',
    updatedAt: '2024-10-29T15:00:00Z',
  },
]

